name: Continuous Integration - Reusable
on:                                                  #on when you want to run this- with workflowcall
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  CI_Steps:
    runs-on: [self-hosted]                                         #added runner that we created
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Import Vault Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault-internal.rajdevops.online:8200/
          token: ${{ secrets.vault_token }}
          tlsSkipVerify: true
          secrets: |
            common/data/common sonarqube_user | sonarqube_user;
            common/data/common sonarqube_password | sonarqube_password ;

      - run: echo ok
        name: Code lint

#      - run: echo ok
#        name: Code Test
      - run: npm install
        name: Install NodeJS modules

      - run: echo npm run test:unit
        name: Code Unit Tests

      - run:  echo npm run test:integration
        name: code Integration Tests

      - run: /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.rajdevops.online:9000 -Dsonar.projectKey=${{ inputs.project-name }} -Dsonar.qualitygate.wait=true -Dsonar_login=${{ steps.vault-secrets.output.sonarqube_user }} -Dsonar_password=${{ steps.vault-secrets.output.sonarqube_password }}
        name: Code Review

      - run: echo ok
        name: Release Software
#