name: Continuous Integration - Reusable
on:                                                  #on when you want to run this- with workflowcall
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  CI_Steps:
    runs-on: [self-hosted]                                         #added runner that we created
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - run: echo ok
        name: Code lint
#      - run: echo ok
#        name: Code Test
      - run: npm install
        name: Install NodeJS modules
      - run: echo npm run test:unit
        name: Code Unit Tests
      - run:  echo npm run test:integration
        name: code Integration Tests
      - run: echo /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.rajdevops.online:9000 -Dsonar.projectKey=${{ inputs.project-name }} -Dsonar.qualitygate.wait=true - ${{ secrets.vault_token }}}
        name: Code Review
      - run: echo ok
        name: Release Software
