name: Release - Reusable
on:                                                  #on when you want to run this- with workflowcall
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      release_archive_file:
        required: true
        type: string
      npm_install:
        required: true
        type: boolean
    secrets:
      vault_token:
        required: true

jobs:
  CI_Steps:
    runs-on: [self-hosted]                                         #added runner that we createdk
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - run: echo npm install
        name: Install NodeJS modules
        if: ${{ inputs.npm_install }}

      - name: Import Vault Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault-internal.rajdevops.online:8200/
          token: ${{ secrets.vault_token }}
          tlsSkipVerify: true
          secrets: |
            common/data/common artifactory_user | artifactory_user;
            common/data/common artifactory_password | artifactory_password ;

    

      - run: echo ${GITHUB_REF_NAME} >version
        name: Create Version File


      - name: Prepare Artifact
        uses: vimtor/action-zip@v1.2
        with:
          files: ${{ inputs.release_archive_file }}
          dest: artifact.zip

      - run: curl -f -v --user ${{ steps.vault-secrets.outputs.artifactory_user }}:${{ steps.vault-secrets.outputs.artifactory_password }} --data-binary @artifact.zip -X PUT "http://artifactory-internal.rajdevops.online:8081/artifactory/${{ inputs.project-name }}/${GITHUB_REF_NAME}.zip"
        name: Upload Artifact
#        if:  ${{ startsWith(github.ref, 'refs/tags/') }}